name: Building
on:
  push:
    branches: [ master ]
jobs:
  debian-12:
    runs-on: ubuntu-latest
    container:
      image: jeonghanlee/debian12-epics
    steps:
      - uses: actions/checkout@v4
      - run: |
          cat /usr/local/setEnv
          . /usr/local/setEnv
          echo "EPICS_BASE:=${EPICS_BASE}" > configure/RELEASE.local
          make
